import { pgTable, text, integer, boolean, timestamp, jsonb, uuid } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  clerkUserId: text('clerk_user_id').primaryKey(),
  email: text('email').notNull(),
  name: text('name').notNull(),
  locale: text('locale').notNull().default('en'),
  dob: text('dob').notNull(),
  birthTime: text('birth_time'),
  birthLocation: jsonb('birth_location').notNull(),
  dominantHand: text('dominant_hand').notNull().$type<'left' | 'right'>(),
  zodiacSign: text('zodiac_sign').notNull(),
  nakshatra: text('nakshatra'),
  lifePathNumber: integer('life_path_number').notNull(),
  expressionNumber: integer('expression_number').notNull(),
  soulUrgeNumber: integer('soul_urge_number').notNull(),
  personalityNumber: integer('personality_number').notNull(),
  subscriptionTier: text('subscription_tier').notNull().default('free').$type<'free' | 'mystic' | 'oracle' | 'sage'>(),
  streakCount: integer('streak_count').notNull().default(0),
  totalReadings: integer('total_readings').notNull().default(0),
  xpPoints: integer('xp_points').notNull().default(0),
  badges: jsonb('badges').notNull().default([]).$type<string[]>(),
  notificationTime: text('notification_time').notNull().default('08:00:00'),
  notificationsEnabled: boolean('notifications_enabled').notNull().default(true),
  region: text('region').notNull().default('us-east').$type<'mumbai' | 'frankfurt' | 'us-east'>(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  lastActiveAt: timestamp('last_active_at', { withTimezone: true }).notNull().defaultNow(),
});

export const readings = pgTable('readings', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').notNull().references(() => users.clerkUserId),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  mode: text('mode').notNull().$type<'standard' | 'love' | 'career' | 'health' | 'spiritual' | 'crystal_ball'>(),
  hand: text('hand').notNull().$type<'left' | 'right' | 'both'>(),
  palmImageUrl: text('palm_image_url').notNull(),
  rawVisionJson: jsonb('raw_vision_json').notNull(),
  narrativeMarkdown: text('narrative_markdown').notNull(),
  luckScore: integer('luck_score').notNull(),
  dominantTrait: text('dominant_trait').notNull(),
  audioUrl: text('audio_url'),
  infographicUrl: text('infographic_url'),
  sharedAt: timestamp('shared_at', { withTimezone: true }),
  visionProvider: text('vision_provider').notNull(),
  synthesisProvider: text('synthesis_provider').notNull(),
  aiCostCents: integer('ai_cost_cents').notNull().default(0),
});

export const dailyOracles = pgTable('daily_oracles', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').notNull().references(() => users.clerkUserId),
  date: text('date').notNull(),
  oracleText: text('oracle_text').notNull(),
  tarotCard: jsonb('tarot_card').notNull(),
  moonPhase: jsonb('moon_phase').notNull(),
  luckScore: integer('luck_score').notNull(),
  luckyColor: text('lucky_color').notNull(),
  luckyNumber: integer('lucky_number').notNull(),
  mantra: text('mantra'),
  mudra: text('mudra'),
  generatedAt: timestamp('generated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const compatibilityReadings = pgTable('compatibility_readings', {
  id: uuid('id').primaryKey().defaultRandom(),
  userAId: text('user_a_id').notNull().references(() => users.clerkUserId),
  userBId: text('user_b_id').references(() => users.clerkUserId),
  userBGuestHash: text('user_b_guest_hash'),
  scores: jsonb('scores').notNull(),
  overallScore: integer('overall_score').notNull(),
  couplePortraitUrl: text('couple_portrait_url'),
  summary: text('summary').notNull(),
  strengths: jsonb('strengths').notNull().$type<string[]>(),
  challenges: jsonb('challenges').notNull().$type<string[]>(),
  advice: text('advice').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const subscriptions = pgTable('subscriptions', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').notNull().references(() => users.clerkUserId),
  tier: text('tier').notNull().$type<'mystic' | 'oracle' | 'sage'>(),
  status: text('status').notNull().$type<'trialing' | 'active' | 'grace' | 'cancelled' | 'expired'>(),
  platform: text('platform').notNull().$type<'ios' | 'android' | 'web'>(),
  revenuecatId: text('revenuecat_id'),
  stripeSubscriptionId: text('stripe_subscription_id'),
  trialUsed: boolean('trial_used').notNull().default(false),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
  renewsAt: timestamp('renews_at', { withTimezone: true }),
  cancelledAt: timestamp('cancelled_at', { withTimezone: true }),
  referrerId: text('referrer_id'),
});

export const birthCharts = pgTable('birth_charts', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').notNull().references(() => users.clerkUserId),
  system: text('system').notNull().$type<'western' | 'vedic'>(),
  planets: jsonb('planets').notNull(),
  houses: jsonb('houses').notNull(),
  aspects: jsonb('aspects').notNull(),
  nakshatras: jsonb('nakshatras'),
  dashaPeriods: jsonb('dasha_periods'),
  chartSvgUrl: text('chart_svg_url').notNull(),
  computedAt: timestamp('computed_at', { withTimezone: true }).notNull().defaultNow(),
});
